### ISSUE TITLE
Moving translations wiki

### ISSUE THREAD

**Issue by hturner** [r-devel/rcwg#46]
From R Contributors Slack:

Move translations wiki to separate site, e.g. bookdown/Quarto/MkDocs, to give more control over layout and make it easier for people to contribute.

This could take over the `translations` repo and we could move the dashboard to a `translations-dashboard` repo so they get deployed at https://contributor.r-project.org/translations and https://contributor.r-project.org/translations-dashboard respectively.

**Comment by jmaspons** [comment]
I can do it. Will go for quarto and gh actions. Could somebody move and create the repos?

**Comment by hturner** [comment]
I have renamed the old translations repo to translations-dashboard and created a new translations repo.

So you should be ready to deploy something to https://contributor.r-project.org/translations. Note that this isn't linked anywhere from the main site yet so is somewhat private until we do that. It would be good to add a link to the dashboard so people can still find that.

**Comment by daroczig** [comment]
If we create a new repo instead of repurposing the old one,  should we migrate the issues as well? E.g. all the weblate related tickets and the weblate project dashboard.

**Comment by mcnanton** [comment]
@jmaspons I would like to collaborate on this with you if needed. I'll be away for a week but can help with this from sept 25 foward.

**Comment by daroczig** [comment]
Once the new GH page is ready, we should probably also set up a blank wiki in the new repo pointing to it, so that the (currently dead) URLs pointing to the original wiki (e.g. https://github.com/r-devel/translations/wiki/Conventions-for-translations) can point the visitor to the right place.

**Comment by hturner** [comment]
@daroczig yes, the current issues are a mix of ones for the dashboard and weblate. I think it would make sense to transfer the weblate ones to the new repo - I'm not sure how easy it is to move a project board, but the issues can be transferred easily enough and if necessary added to a new project board.

**Comment by daroczig** [comment]
I've migrated over all weblate-related tickets and also reassociated the weblate project to the new repo :+1:

**Comment by jmaspons** [comment]
The wiki is now quarto website! Take a look at https://github.com/r-devel/translations (all wiki history preserved)

I added a github workflow to render and publish to gh-pages, but we have a custom domain and I think it should be configured differently. Can somebody configure the deployment of the web?

**Comment by jmaspons** [comment]
Web deployed to https://contributor.r-project.org/translations/

**Comment by jmaspons** [comment]
Most of the contributors agreed to license the web to CC BY 4.0 https://r-contributors.slack.com/archives/C0210D7EN1X/p1695743347136759

Waiting for confirmation from @alswajiab , @bjungbogati , @imanalhasani , @MichaelChirico & @shun2wang ,

**Comment by jmaspons** [comment]
I would say this task is done. I created a home page in the wiki pointing to the web, but no redirects for each page. Is this enough?

**Comment by willingc** [comment]
Devguide is updated now.

**Comment by hturner** [comment]
I have also update the navigation on the main contributor page, so people can find the new translation pages from there!

I think we have done enough now to close this issue - thanks everyone!

**Comment by jmaspons** [comment]
Missing https://github.com/r-devel/translations-dashboard/pull/34
